-- Filahi Database Schema — Phase 0 Foundation

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Helper functions to avoid RLS recursion in admin/courier checks
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin');
$$;

CREATE OR REPLACE FUNCTION public.has_driver_role(required_role TEXT)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (SELECT 1 FROM public.driver_profiles WHERE id = auth.uid() AND role = required_role);
$$;

CREATE OR REPLACE FUNCTION public.has_role(required_role TEXT)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = required_role);
$$;

CREATE TABLE IF NOT EXISTS profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name       TEXT NOT NULL,
  phone_number    TEXT UNIQUE NOT NULL,
  role            TEXT NOT NULL CHECK (role IN ('farmer', 'driver', 'courier', 'buyer', 'admin')),
  whatsapp_id     TEXT UNIQUE,
  avatar_url      TEXT,
  preferred_lang  TEXT DEFAULT 'ar' CHECK (preferred_lang IN ('ar', 'fr')),
  is_active       BOOLEAN DEFAULT TRUE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own profile" ON profiles;
CREATE POLICY "Users read own profile"
  ON profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users update own profile" ON profiles;
CREATE POLICY "Users update own profile"
  ON profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admin reads all profiles" ON profiles;
CREATE POLICY "Admin reads all profiles"
  ON profiles FOR SELECT USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS driver_profiles (
  id                    UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  cin_number            TEXT UNIQUE NOT NULL,
  cin_photo_url         TEXT NOT NULL,
  carte_grise_url       TEXT NOT NULL,
  vehicle_type          TEXT NOT NULL CHECK (vehicle_type IN ('isuzu', 'dmax', 'scooter', 'berlingo', 'fiorino', 'other')),
  vehicle_plate         TEXT UNIQUE NOT NULL,
  role                  TEXT NOT NULL DEFAULT 'long_haul' CHECK (role IN ('long_haul', 'courier')),
  trust_tier            INT DEFAULT 1 CHECK (trust_tier BETWEEN 1 AND 3),
  trust_score           NUMERIC(4,2) DEFAULT 0,
  total_trips           INT DEFAULT 0,
  is_verified           BOOLEAN DEFAULT FALSE,
  max_cargo_value_tnd   INT DEFAULT 200000,
  created_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE driver_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Driver reads own profile" ON driver_profiles;
CREATE POLICY "Driver reads own profile"
  ON driver_profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admin manages driver profiles" ON driver_profiles;
CREATE POLICY "Admin manages driver profiles"
  ON driver_profiles FOR ALL USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS hubs (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name          TEXT NOT NULL,
  address       TEXT NOT NULL,
  coordinates   GEOMETRY(Point, 4326) NOT NULL,
  manager_id    UUID REFERENCES profiles(id),
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery_zones (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  hub_id      UUID NOT NULL REFERENCES hubs(id),
  name        TEXT NOT NULL,
  boundary    GEOMETRY(Polygon, 4326) NOT NULL,
  is_active   BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_zones_boundary ON delivery_zones USING GIST (boundary);

CREATE TABLE IF NOT EXISTS inventory_items (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id               UUID NOT NULL REFERENCES profiles(id),
  product_name            TEXT NOT NULL,
  product_category        TEXT NOT NULL CHECK (product_category IN (
                            'vegetables', 'fruit', 'eggs', 'honey',
                            'olive_oil', 'legumes', 'grains', 'herbs', 'other'
                          )),
  quantity                NUMERIC NOT NULL CHECK (quantity > 0),
  unit                    TEXT NOT NULL CHECK (unit IN ('kg', 'hara', 'litra', 'crate', 'piece', 'ton')),
  asking_price_millimes   INT NOT NULL CHECK (asking_price_millimes > 0),
  platform_price_millimes INT,
  location_name           TEXT NOT NULL,
  coordinates             GEOMETRY(Point, 4326),
  harvest_date            DATE,
  shelf_life_days         INT,
  expires_at              TIMESTAMPTZ,
  status                  TEXT NOT NULL DEFAULT 'pending_confirmation'
                            CHECK (status IN ('pending_confirmation', 'available', 'reserved', 'sold', 'expired')),
  source                  TEXT DEFAULT 'whatsapp_bot' CHECK (source IN ('whatsapp_bot', 'admin', 'web')),
  raw_transcription       TEXT,
  ai_confidence_score     NUMERIC(3,2),
  whatsapp_message_id     TEXT UNIQUE,
  notes                   TEXT,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventory_coordinates ON inventory_items USING GIST (coordinates);
CREATE INDEX IF NOT EXISTS idx_inventory_status ON inventory_items (status);
CREATE INDEX IF NOT EXISTS idx_inventory_farmer ON inventory_items (farmer_id);

CREATE OR REPLACE FUNCTION compute_platform_price()
RETURNS TRIGGER AS $$
BEGIN
  NEW.platform_price_millimes := ROUND(NEW.asking_price_millimes * 1.12);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_platform_price ON inventory_items;
CREATE TRIGGER trg_platform_price
  BEFORE INSERT OR UPDATE OF asking_price_millimes ON inventory_items
  FOR EACH ROW EXECUTE FUNCTION compute_platform_price();

ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view available inventory" ON inventory_items;
CREATE POLICY "Anyone can view available inventory"
  ON inventory_items FOR SELECT USING (status = 'available');

DROP POLICY IF EXISTS "Farmers manage own inventory" ON inventory_items;
CREATE POLICY "Farmers manage own inventory"
  ON inventory_items FOR ALL USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "Admin manages all inventory" ON inventory_items;
CREATE POLICY "Admin manages all inventory"
  ON inventory_items FOR ALL USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS orders (
  id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  buyer_id              UUID NOT NULL REFERENCES profiles(id),
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'confirmed', 'in_transit', 'delivered', 'cancelled', 'refunded')),
  total_price_millimes  INT NOT NULL,
  commission_millimes   INT NOT NULL,
  delivery_zone_id      UUID REFERENCES delivery_zones(id),
  delivery_address      TEXT,
  delivery_notes        TEXT,
  is_recurring          BOOLEAN DEFAULT FALSE,
  recurrence_day        INT CHECK (recurrence_day BETWEEN 0 AND 6),
  recurrence_interval   TEXT CHECK (recurrence_interval IN ('weekly', 'biweekly', 'monthly')),
  next_recurrence_at    TIMESTAMPTZ,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Buyers read own orders" ON orders;
CREATE POLICY "Buyers read own orders"
  ON orders FOR SELECT USING (auth.uid() = buyer_id);

DROP POLICY IF EXISTS "Admin reads all orders" ON orders;
CREATE POLICY "Admin reads all orders"
  ON orders FOR ALL USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS order_items (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  inventory_item_id     BIGINT NOT NULL REFERENCES inventory_items(id),
  quantity              NUMERIC NOT NULL,
  unit_price_millimes   INT NOT NULL,
  total_millimes        INT NOT NULL
);

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Buyers read own order items" ON order_items;
CREATE POLICY "Buyers read own order items"
  ON order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM orders WHERE id = order_id AND buyer_id = auth.uid())
  );

CREATE TABLE IF NOT EXISTS trips (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  driver_id               UUID REFERENCES driver_profiles(id),
  order_ids               UUID[],
  origin_location_name    TEXT NOT NULL,
  destination_location_name TEXT,
  origin_coordinates      GEOMETRY(Point, 4326),
  hub_id                  UUID REFERENCES hubs(id),
  status                  TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN (
                              'pending', 'accepted', 'in_transit',
                              'arrived_hub', 'delivered', 'settled', 'disputed'
                            )),
  otp_pickup              TEXT NOT NULL,
  otp_delivery            TEXT NOT NULL,
  cargo_value_millimes    INT NOT NULL,
  driver_fee_millimes     INT NOT NULL,
  platform_fee_millimes   INT NOT NULL,
  last_known_lat          NUMERIC(10, 7),
  last_known_lng          NUMERIC(10, 7),
  last_ping_at            TIMESTAMPTZ,
  estimated_arrival_at    TIMESTAMPTZ,
  accepted_at             TIMESTAMPTZ,
  picked_up_at            TIMESTAMPTZ,
  delivered_at            TIMESTAMPTZ,
  settled_at              TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trips_status ON trips (status);
CREATE INDEX IF NOT EXISTS idx_trips_driver ON trips (driver_id);

CREATE OR REPLACE FUNCTION validate_pickup_otp(trip_id UUID, otp_input TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_trip trips%ROWTYPE;
BEGIN
  SELECT * INTO v_trip FROM trips WHERE id = trip_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'trip_not_found');
  END IF;

  IF v_trip.status != 'accepted' THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_status');
  END IF;

  IF v_trip.otp_pickup != otp_input THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_otp');
  END IF;

  UPDATE trips SET status = 'in_transit', picked_up_at = NOW() WHERE id = trip_id;

  RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION validate_delivery_otp(trip_id UUID, otp_input TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_trip trips%ROWTYPE;
BEGIN
  SELECT * INTO v_trip FROM trips WHERE id = trip_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'trip_not_found');
  END IF;

  IF v_trip.status NOT IN ('in_transit', 'arrived_hub') THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_status');
  END IF;

  IF v_trip.otp_delivery != otp_input THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_otp');
  END IF;

  UPDATE trips SET
    status = 'delivered',
    delivered_at = NOW()
  WHERE id = trip_id;

  RETURN jsonb_build_object('success', true);
END;
$$;

ALTER TABLE trips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Drivers read own trips" ON trips;
CREATE POLICY "Drivers read own trips"
  ON trips FOR SELECT USING (
    EXISTS (SELECT 1 FROM driver_profiles WHERE id = auth.uid() AND id = driver_id)
  );

DROP POLICY IF EXISTS "Admin manages all trips" ON trips;
CREATE POLICY "Admin manages all trips"
  ON trips FOR ALL USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS trip_location_cache (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id     UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  lat         NUMERIC(10, 7) NOT NULL,
  lng         NUMERIC(10, 7) NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL,
  synced_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_location_cache_trip ON trip_location_cache (trip_id, recorded_at);

CREATE OR REPLACE FUNCTION cleanup_old_location_cache()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM trip_location_cache WHERE synced_at < NOW() - INTERVAL '48 hours';
END;
$$;

CREATE TABLE IF NOT EXISTS whatsapp_messages (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_message_id     TEXT UNIQUE NOT NULL,
  direction         TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  wa_sender_id      TEXT NOT NULL,
  profile_id        UUID REFERENCES profiles(id),
  message_type      TEXT NOT NULL CHECK (message_type IN ('text', 'audio', 'button', 'template')),
  content_text      TEXT,
  audio_url         TEXT,
  audio_transcribed TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION cleanup_old_whatsapp_messages()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM whatsapp_messages WHERE created_at < NOW() - INTERVAL '90 days';
END;
$$;

CREATE TABLE IF NOT EXISTS disputes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id           UUID REFERENCES trips(id),
  raised_by         UUID REFERENCES profiles(id),
  dispute_type      TEXT NOT NULL CHECK (dispute_type IN (
                      'cargo_theft', 'otp_failure', 'gps_loss',
                      'quality_issue', 'no_show', 'other'
                    )),
  description       TEXT,
  status            TEXT DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'resolved', 'escalated')),
  resolution_notes  TEXT,
  resolved_by       UUID REFERENCES profiles(id),
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  resolved_at       TIMESTAMPTZ
);

ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin manages disputes" ON disputes;
CREATE POLICY "Admin manages disputes"
  ON disputes FOR ALL USING (
    public.is_admin()
  );

CREATE TABLE IF NOT EXISTS ledger_entries (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id             UUID REFERENCES trips(id),
  order_id            UUID REFERENCES orders(id),
  entry_type          TEXT NOT NULL CHECK (entry_type IN (
                        'buyer_payment', 'platform_commission',
                        'driver_fee', 'farmer_payout', 'refund', 'adjustment'
                      )),
  amount_millimes     INT NOT NULL,
  currency            TEXT DEFAULT 'TND',
  party_id            UUID REFERENCES profiles(id),
  payment_method      TEXT CHECK (payment_method IN ('cod', 'flouci', 'walletii', 'bank', 'manual')),
  reference           TEXT,
  notes               TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin reads ledger" ON ledger_entries;
CREATE POLICY "Admin reads ledger"
  ON ledger_entries FOR SELECT USING (
    public.is_admin()
  );

DROP POLICY IF EXISTS "Ledger is append-only via server" ON ledger_entries;
CREATE POLICY "Ledger is append-only via server"
  ON ledger_entries FOR INSERT WITH CHECK (TRUE);

-- Seed data: Default hub (only if not already seeded)
INSERT INTO hubs (name, address, coordinates)
SELECT 'Hub Bir El Kassaa', 'Route de Sfax, Bir El Kassaa, Ben Arous',
       ST_SetSRID(ST_MakePoint(10.2417, 36.7525), 4326)
WHERE NOT EXISTS (
  SELECT 1 FROM hubs WHERE name = 'Hub Bir El Kassaa'
);
