-- Filahi Rating System — Phase 2 Enhancement

CREATE TABLE IF NOT EXISTS ratings (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  trip_id         UUID REFERENCES trips(id),
  reviewer_id     UUID NOT NULL REFERENCES profiles(id),
  target_id       UUID NOT NULL REFERENCES profiles(id),
  target_type     TEXT NOT NULL CHECK (target_type IN ('driver', 'farmer', 'product')),
  score           INT NOT NULL CHECK (score BETWEEN 1 AND 5),
  review_text     TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(order_id, reviewer_id, target_type)
);

ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read ratings" ON ratings;
CREATE POLICY "Anyone can read ratings"
  ON ratings FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Buyers create ratings" ON ratings;
CREATE POLICY "Buyers create ratings"
  ON ratings FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM orders WHERE id = order_id AND buyer_id = auth.uid())
  );

DROP POLICY IF EXISTS "Admin manages ratings" ON ratings;
CREATE POLICY "Admin manages ratings"
  ON ratings FOR ALL USING (
    auth.is_admin()
  );

CREATE OR REPLACE FUNCTION update_driver_trust_score()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.target_type = 'driver' THEN
    UPDATE driver_profiles
    SET trust_score = (
      SELECT ROUND(AVG(score)::numeric, 2)
      FROM ratings
      WHERE target_id = NEW.target_id AND target_type = 'driver'
    )
    WHERE id = NEW.target_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_update_driver_score ON ratings;
CREATE TRIGGER trg_update_driver_score
  AFTER INSERT OR UPDATE ON ratings
  FOR EACH ROW
  WHEN (NEW.target_type = 'driver')
  EXECUTE FUNCTION update_driver_trust_score();
