-- 005: Group Buy (pooled orders)

CREATE TABLE group_buys (
  id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  creator_id            UUID NOT NULL REFERENCES profiles(id),
  inventory_item_id     BIGINT NOT NULL REFERENCES inventory_items(id),
  target_quantity       NUMERIC NOT NULL CHECK (target_quantity > 0),
  current_quantity      NUMERIC NOT NULL DEFAULT 0 CHECK (current_quantity >= 0),
  unit                  TEXT NOT NULL,
  unit_price_millimes   INT NOT NULL CHECK (unit_price_millimes > 0),
  status                TEXT NOT NULL DEFAULT 'open'
                          CHECK (status IN ('open', 'fulfilled', 'cancelled')),
  expires_at            TIMESTAMPTZ NOT NULL,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  fulfilled_at          TIMESTAMPTZ,
  cancelled_at          TIMESTAMPTZ
);

CREATE INDEX idx_group_buys_status ON group_buys (status);
CREATE INDEX idx_group_buys_item ON group_buys (inventory_item_id);

CREATE TABLE group_buy_participants (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_buy_id  UUID NOT NULL REFERENCES group_buys(id) ON DELETE CASCADE,
  buyer_id      UUID NOT NULL REFERENCES profiles(id),
  quantity      NUMERIC NOT NULL CHECK (quantity > 0),
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (group_buy_id, buyer_id)
);

CREATE INDEX idx_participants_group ON group_buy_participants (group_buy_id);

ALTER TABLE group_buys ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_buy_participants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read open group buys"
  ON group_buys FOR SELECT USING (
    status = 'open' OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') OR
    creator_id = auth.uid()
  );

CREATE POLICY "Authenticated users can create group buys"
  ON group_buys FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'buyer')
  );

CREATE POLICY "Creator or admin can update group buys"
  ON group_buys FOR UPDATE USING (
    creator_id = auth.uid() OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Buyers read own participations"
  ON group_buy_participants FOR SELECT USING (buyer_id = auth.uid());

CREATE POLICY "Buyers can join group buys"
  ON group_buy_participants FOR INSERT WITH CHECK (
    buyer_id = auth.uid()
  );

CREATE OR REPLACE FUNCTION join_group_buy(group_buy_id UUID, join_quantity NUMERIC)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_group group_buys%ROWTYPE;
BEGIN
  SELECT * INTO v_group FROM group_buys WHERE id = group_buy_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'group_buy_not_found');
  END IF;

  IF v_group.status != 'open' THEN
    RETURN jsonb_build_object('success', false, 'error', 'group_buy_not_open');
  END IF;

  IF (v_group.current_quantity + join_quantity) > v_group.target_quantity THEN
    RETURN jsonb_build_object('success', false, 'error', 'exceeds_target_quantity');
  END IF;

  IF v_group.expires_at < NOW() THEN
    RETURN jsonb_build_object('success', false, 'error', 'group_buy_expired');
  END IF;

  INSERT INTO group_buy_participants (group_buy_id, buyer_id, quantity)
  VALUES (group_buy_id, auth.uid(), join_quantity);

  UPDATE group_buys SET
    current_quantity = current_quantity + join_quantity,
    status = CASE
      WHEN (current_quantity + join_quantity) >= target_quantity THEN 'fulfilled'
      ELSE 'open'
    END,
    fulfilled_at = CASE
      WHEN (current_quantity + join_quantity) >= target_quantity THEN NOW()
      ELSE NULL
    END
  WHERE id = group_buy_id;

  RETURN jsonb_build_object('success', true);
END;
$$;
